// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(drive9_mobile_coreFFI)
import drive9_mobile_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_drive9_mobile_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_drive9_mobile_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDrive9MobileCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Cooperative cancellation handle. Construct one on the caller side, pass it
 * into `upload_file` / `download_file` / `patch_file_parts`, and call
 * `cancel()` from another task / thread to abort the transfer.
 *
 * Cancellation is cooperative: in-flight HTTP requests are dropped when the
 * transfer future is racing against `cancel()`, which terminates the
 * underlying connection. Partial uploads on the server are NOT explicitly
 * aborted (drive9-rs handles its own cleanup on internal errors, but a
 * drop-on-cancel from outside cannot reach those abort paths). Server-side
 * upload sessions typically expire.
 */
public protocol Drive9CancelTokenProtocol: AnyObject, Sendable {
    
    func cancel() 
    
    func isCancelled()  -> Bool
    
}
/**
 * Cooperative cancellation handle. Construct one on the caller side, pass it
 * into `upload_file` / `download_file` / `patch_file_parts`, and call
 * `cancel()` from another task / thread to abort the transfer.
 *
 * Cancellation is cooperative: in-flight HTTP requests are dropped when the
 * transfer future is racing against `cancel()`, which terminates the
 * underlying connection. Partial uploads on the server are NOT explicitly
 * aborted (drive9-rs handles its own cleanup on internal errors, but a
 * drop-on-cancel from outside cannot reach those abort paths). Server-side
 * upload sessions typically expire.
 */
open class Drive9CancelToken: Drive9CancelTokenProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_drive9_mobile_core_fn_clone_drive9canceltoken(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_drive9_mobile_core_fn_constructor_drive9canceltoken_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_drive9_mobile_core_fn_free_drive9canceltoken(handle, $0) }
    }

    

    
open func cancel()  {try! rustCall() {
    uniffi_drive9_mobile_core_fn_method_drive9canceltoken_cancel(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func isCancelled() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_drive9_mobile_core_fn_method_drive9canceltoken_is_cancelled(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9CancelToken: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Drive9CancelToken

    public static func lift(_ handle: UInt64) throws -> Drive9CancelToken {
        return Drive9CancelToken(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Drive9CancelToken) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9CancelToken {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Drive9CancelToken, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9CancelToken_lift(_ handle: UInt64) throws -> Drive9CancelToken {
    return try FfiConverterTypeDrive9CancelToken.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9CancelToken_lower(_ value: Drive9CancelToken) -> UInt64 {
    return FfiConverterTypeDrive9CancelToken.lower(value)
}






public protocol Drive9MobileClientProtocol: AnyObject, Sendable {
    
    func copy(srcPath: String, dstPath: String) throws 
    
    func delete(path: String) throws 
    
    /**
     * Stream `remote_path` to disk at `local_path`. Progress is emitted
     * per chunk written (precise: bytes transferred always equal bytes
     * already on disk). Cancellation is cooperative — checked between
     * chunks and via `tokio::select!` so a cancel while a chunk read is
     * in flight terminates the underlying connection. A cancelled
     * transfer surfaces as `Drive9Exception` with `code = "cancelled"`.
     *
     * On any failure (network error, cancellation, write error) the
     * partial local file is deleted so callers do not mistake a partial
     * download for the full file. Successful downloads leave the file
     * in place.
     */
    func downloadFile(remotePath: String, localPath: String, progress: Drive9ProgressListener?, cancel: Drive9CancelToken?) throws 
    
    /**
     * Search by metadata. `params` is forwarded verbatim to `drive9-rs` so
     * URL encoding and server-side semantics stay in one place; the wrapper
     * does not interpret keys.
     */
    func find(pathPrefix: String, params: [String: String]) throws  -> [Drive9SearchResult]
    
    /**
     * Search by content. `limit` of 0 (or negative) lets the server pick.
     */
    func grep(query: String, pathPrefix: String, limit: Int32) throws  -> [Drive9SearchResult]
    
    func list(path: String) throws  -> [Drive9FileInfo]
    
    func mkdir(path: String) throws 
    
    /**
     * Patch specific parts of a remote file using bytes read from
     * `local_path`. `dirty_parts` are 1-based part numbers; the server
     * keeps the unlisted parts. `part_size` overrides the server default
     * when set. `new_size` is the total file size after patching.
     *
     * Input validation (rejected with `code = "other"`):
     * - every `part_num >= 1`
     * - `part_size`, if set, must be `> 0`
     * - `new_size >= 0`
     *
     * Cancellation / progress are NOT supported in this iteration;
     * dropping the call mid-patch leaves the server-side multipart upload
     * to expire on its own. Callers that need cancel should compose with
     * external task cancellation and accept the same caveat.
     */
    func patchFileParts(localPath: String, remotePath: String, dirtyParts: [Int32], newSize: Int64, partSize: Int64?, expectedRevision: Int64?) throws 
    
    func read(path: String) throws  -> Data
    
    func rename(oldPath: String, newPath: String) throws 
    
    /**
     * Run a SQL query. Each result row is returned as a JSON-encoded string
     * so the FFI surface stays free of arbitrary JSON values; consumers
     * parse with their preferred JSON library. The wrapper does not
     * interpret column names or types.
     */
    func sql(query: String) throws  -> [String]
    
    func stat(path: String) throws  -> Drive9StatResult
    
    /**
     * Write `data` to `path`. When `expected_revision` is provided, the write
     * is conditional: a 409 Conflict surfaces as `Drive9Exception` with
     * `code = "conflict"` and `server_revision` set.
     */
    func write(path: String, data: Data, expectedRevision: Int64?) throws 
    
}
open class Drive9MobileClient: Drive9MobileClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_drive9_mobile_core_fn_clone_drive9mobileclient(self.handle, $0) }
    }
    /**
     * Build a client bound to `base_url` and authenticated with `api_key`.
     * Each client owns a multi-thread Tokio runtime; share one client across
     * the app rather than constructing per-call.
     */
public convenience init(baseUrl: String, apiKey: String) {
    let handle =
        try! rustCall() {
    uniffi_drive9_mobile_core_fn_constructor_drive9mobileclient_new(
        FfiConverterString.lower(baseUrl),
        FfiConverterString.lower(apiKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_drive9_mobile_core_fn_free_drive9mobileclient(handle, $0) }
    }

    

    
open func copy(srcPath: String, dstPath: String)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_copy(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(srcPath),
        FfiConverterString.lower(dstPath),$0
    )
}
}
    
open func delete(path: String)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
}
}
    
    /**
     * Stream `remote_path` to disk at `local_path`. Progress is emitted
     * per chunk written (precise: bytes transferred always equal bytes
     * already on disk). Cancellation is cooperative — checked between
     * chunks and via `tokio::select!` so a cancel while a chunk read is
     * in flight terminates the underlying connection. A cancelled
     * transfer surfaces as `Drive9Exception` with `code = "cancelled"`.
     *
     * On any failure (network error, cancellation, write error) the
     * partial local file is deleted so callers do not mistake a partial
     * download for the full file. Successful downloads leave the file
     * in place.
     */
open func downloadFile(remotePath: String, localPath: String, progress: Drive9ProgressListener?, cancel: Drive9CancelToken?)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_download_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(remotePath),
        FfiConverterString.lower(localPath),
        FfiConverterOptionTypeDrive9ProgressListener.lower(progress),
        FfiConverterOptionTypeDrive9CancelToken.lower(cancel),$0
    )
}
}
    
    /**
     * Search by metadata. `params` is forwarded verbatim to `drive9-rs` so
     * URL encoding and server-side semantics stay in one place; the wrapper
     * does not interpret keys.
     */
open func find(pathPrefix: String, params: [String: String])throws  -> [Drive9SearchResult]  {
    return try  FfiConverterSequenceTypeDrive9SearchResult.lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_find(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(pathPrefix),
        FfiConverterDictionaryStringString.lower(params),$0
    )
})
}
    
    /**
     * Search by content. `limit` of 0 (or negative) lets the server pick.
     */
open func grep(query: String, pathPrefix: String, limit: Int32)throws  -> [Drive9SearchResult]  {
    return try  FfiConverterSequenceTypeDrive9SearchResult.lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_grep(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterString.lower(pathPrefix),
        FfiConverterInt32.lower(limit),$0
    )
})
}
    
open func list(path: String)throws  -> [Drive9FileInfo]  {
    return try  FfiConverterSequenceTypeDrive9FileInfo.lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
})
}
    
open func mkdir(path: String)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_mkdir(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
}
}
    
    /**
     * Patch specific parts of a remote file using bytes read from
     * `local_path`. `dirty_parts` are 1-based part numbers; the server
     * keeps the unlisted parts. `part_size` overrides the server default
     * when set. `new_size` is the total file size after patching.
     *
     * Input validation (rejected with `code = "other"`):
     * - every `part_num >= 1`
     * - `part_size`, if set, must be `> 0`
     * - `new_size >= 0`
     *
     * Cancellation / progress are NOT supported in this iteration;
     * dropping the call mid-patch leaves the server-side multipart upload
     * to expire on its own. Callers that need cancel should compose with
     * external task cancellation and accept the same caveat.
     */
open func patchFileParts(localPath: String, remotePath: String, dirtyParts: [Int32], newSize: Int64, partSize: Int64?, expectedRevision: Int64?)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_patch_file_parts(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(localPath),
        FfiConverterString.lower(remotePath),
        FfiConverterSequenceInt32.lower(dirtyParts),
        FfiConverterInt64.lower(newSize),
        FfiConverterOptionInt64.lower(partSize),
        FfiConverterOptionInt64.lower(expectedRevision),$0
    )
}
}
    
open func read(path: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_read(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
})
}
    
open func rename(oldPath: String, newPath: String)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_rename(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(oldPath),
        FfiConverterString.lower(newPath),$0
    )
}
}
    
    /**
     * Run a SQL query. Each result row is returned as a JSON-encoded string
     * so the FFI surface stays free of arbitrary JSON values; consumers
     * parse with their preferred JSON library. The wrapper does not
     * interpret column names or types.
     */
open func sql(query: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_sql(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func stat(path: String)throws  -> Drive9StatResult  {
    return try  FfiConverterTypeDrive9StatResult_lift(try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_stat(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Write `data` to `path`. When `expected_revision` is provided, the write
     * is conditional: a 409 Conflict surfaces as `Drive9Exception` with
     * `code = "conflict"` and `server_revision` set.
     */
open func write(path: String, data: Data, expectedRevision: Int64?)throws   {try rustCallWithError(FfiConverterTypeDrive9Exception_lift) {
    uniffi_drive9_mobile_core_fn_method_drive9mobileclient_write(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterData.lower(data),
        FfiConverterOptionInt64.lower(expectedRevision),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9MobileClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Drive9MobileClient

    public static func lift(_ handle: UInt64) throws -> Drive9MobileClient {
        return Drive9MobileClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Drive9MobileClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9MobileClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Drive9MobileClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9MobileClient_lift(_ handle: UInt64) throws -> Drive9MobileClient {
    return try FfiConverterTypeDrive9MobileClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9MobileClient_lower(_ value: Drive9MobileClient) -> UInt64 {
    return FfiConverterTypeDrive9MobileClient.lower(value)
}






/**
 * Foreign-implemented progress callback. UniFFI marshals this into a
 * Kotlin interface and a Swift protocol; consumers implement
 * `on_progress(transferred, total)`.
 *
 * `total` is 0 when the total size is unknown (e.g. download without a
 * Content-Length). Implementations must be cheap; this is called per chunk
 * during transfer.
 */
public protocol Drive9ProgressListener: AnyObject, Sendable {
    
    func onProgress(transferred: UInt64, total: UInt64) 
    
}
/**
 * Foreign-implemented progress callback. UniFFI marshals this into a
 * Kotlin interface and a Swift protocol; consumers implement
 * `on_progress(transferred, total)`.
 *
 * `total` is 0 when the total size is unknown (e.g. download without a
 * Content-Length). Implementations must be cheap; this is called per chunk
 * during transfer.
 */
open class Drive9ProgressListenerImpl: Drive9ProgressListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_drive9_mobile_core_fn_clone_drive9progresslistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_drive9_mobile_core_fn_free_drive9progresslistener(handle, $0) }
    }

    

    
open func onProgress(transferred: UInt64, total: UInt64)  {try! rustCall() {
    uniffi_drive9_mobile_core_fn_method_drive9progresslistener_on_progress(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(transferred),
        FfiConverterUInt64.lower(total),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDrive9ProgressListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceDrive9ProgressListener = UniffiVTableCallbackInterfaceDrive9ProgressListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeDrive9ProgressListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface Drive9ProgressListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeDrive9ProgressListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface Drive9ProgressListener: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            transferred: UInt64,
            total: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeDrive9ProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     transferred: try FfiConverterUInt64.lift(transferred),
                     total: try FfiConverterUInt64.lift(total)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceDrive9ProgressListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceDrive9ProgressListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitDrive9ProgressListener() {
    uniffi_drive9_mobile_core_fn_init_callback_vtable_drive9progresslistener(UniffiCallbackInterfaceDrive9ProgressListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9ProgressListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<Drive9ProgressListener>()

    typealias FfiType = UInt64
    typealias SwiftType = Drive9ProgressListener

    public static func lift(_ handle: UInt64) throws -> Drive9ProgressListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return Drive9ProgressListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: Drive9ProgressListener) -> UInt64 {
         if let rustImpl = value as? Drive9ProgressListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9ProgressListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Drive9ProgressListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9ProgressListener_lift(_ handle: UInt64) throws -> Drive9ProgressListener {
    return try FfiConverterTypeDrive9ProgressListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9ProgressListener_lower(_ value: Drive9ProgressListener) -> UInt64 {
    return FfiConverterTypeDrive9ProgressListener.lower(value)
}




public struct Drive9FileInfo: Equatable, Hashable {
    public var name: String
    public var size: Int64
    public var isDir: Bool
    /**
     * Unix timestamp in seconds, if the server reported it.
     */
    public var mtimeUnix: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, size: Int64, isDir: Bool, 
        /**
         * Unix timestamp in seconds, if the server reported it.
         */mtimeUnix: Int64?) {
        self.name = name
        self.size = size
        self.isDir = isDir
        self.mtimeUnix = mtimeUnix
    }

    

    
}

#if compiler(>=6)
extension Drive9FileInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9FileInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9FileInfo {
        return
            try Drive9FileInfo(
                name: FfiConverterString.read(from: &buf), 
                size: FfiConverterInt64.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf), 
                mtimeUnix: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Drive9FileInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt64.write(value.size, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
        FfiConverterOptionInt64.write(value.mtimeUnix, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9FileInfo_lift(_ buf: RustBuffer) throws -> Drive9FileInfo {
    return try FfiConverterTypeDrive9FileInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9FileInfo_lower(_ value: Drive9FileInfo) -> RustBuffer {
    return FfiConverterTypeDrive9FileInfo.lower(value)
}


public struct Drive9SearchResult: Equatable, Hashable {
    public var path: String
    public var name: String
    public var sizeBytes: Int64
    /**
     * Optional search relevance score, when the server returns one.
     */
    public var score: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, name: String, sizeBytes: Int64, 
        /**
         * Optional search relevance score, when the server returns one.
         */score: Double?) {
        self.path = path
        self.name = name
        self.sizeBytes = sizeBytes
        self.score = score
    }

    

    
}

#if compiler(>=6)
extension Drive9SearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9SearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9SearchResult {
        return
            try Drive9SearchResult(
                path: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                sizeBytes: FfiConverterInt64.read(from: &buf), 
                score: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Drive9SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt64.write(value.sizeBytes, into: &buf)
        FfiConverterOptionDouble.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9SearchResult_lift(_ buf: RustBuffer) throws -> Drive9SearchResult {
    return try FfiConverterTypeDrive9SearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9SearchResult_lower(_ value: Drive9SearchResult) -> RustBuffer {
    return FfiConverterTypeDrive9SearchResult.lower(value)
}


public struct Drive9StatResult: Equatable, Hashable {
    public var size: Int64
    public var isDir: Bool
    public var revision: Int64
    /**
     * Unix timestamp in seconds, if the server reported it.
     */
    public var mtimeUnix: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(size: Int64, isDir: Bool, revision: Int64, 
        /**
         * Unix timestamp in seconds, if the server reported it.
         */mtimeUnix: Int64?) {
        self.size = size
        self.isDir = isDir
        self.revision = revision
        self.mtimeUnix = mtimeUnix
    }

    

    
}

#if compiler(>=6)
extension Drive9StatResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9StatResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9StatResult {
        return
            try Drive9StatResult(
                size: FfiConverterInt64.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf), 
                revision: FfiConverterInt64.read(from: &buf), 
                mtimeUnix: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Drive9StatResult, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.size, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
        FfiConverterInt64.write(value.revision, into: &buf)
        FfiConverterOptionInt64.write(value.mtimeUnix, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9StatResult_lift(_ buf: RustBuffer) throws -> Drive9StatResult {
    return try FfiConverterTypeDrive9StatResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9StatResult_lower(_ value: Drive9StatResult) -> RustBuffer {
    return FfiConverterTypeDrive9StatResult.lower(value)
}


/**
 * Flat error surface for Kotlin / Swift. We keep a single variant so callers
 * always match the same shape; the `code` field distinguishes underlying
 * causes without leaking Rust enum layout across FFI.
 */
public enum Drive9Exception: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Drive9(
        /**
         * Stable error code: "http_status", "conflict", "request", "json",
         * "io", or "other".
         */code: String, 
        /**
         * HTTP status code when the error originated from a server response.
         */statusCode: Int32?, 
        /**
         * Human-readable message. Named `detail` because Kotlin's
         * `Throwable.message` is already provided by UniFFI as a debug-style
         * summary of the variant.
         */detail: String, 
        /**
         * Server-reported revision for 409 conflicts; preserved so conditional
         * writes can retry against the latest revision.
         */serverRevision: Int64?
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Drive9Exception: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrive9Exception: FfiConverterRustBuffer {
    typealias SwiftType = Drive9Exception

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drive9Exception {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Drive9(
            code: try FfiConverterString.read(from: &buf), 
            statusCode: try FfiConverterOptionInt32.read(from: &buf), 
            detail: try FfiConverterString.read(from: &buf), 
            serverRevision: try FfiConverterOptionInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Drive9Exception, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Drive9(code,statusCode,detail,serverRevision):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(code, into: &buf)
            FfiConverterOptionInt32.write(statusCode, into: &buf)
            FfiConverterString.write(detail, into: &buf)
            FfiConverterOptionInt64.write(serverRevision, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9Exception_lift(_ buf: RustBuffer) throws -> Drive9Exception {
    return try FfiConverterTypeDrive9Exception.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrive9Exception_lower(_ value: Drive9Exception) -> RustBuffer {
    return FfiConverterTypeDrive9Exception.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDrive9CancelToken: FfiConverterRustBuffer {
    typealias SwiftType = Drive9CancelToken?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDrive9CancelToken.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDrive9CancelToken.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDrive9ProgressListener: FfiConverterRustBuffer {
    typealias SwiftType = Drive9ProgressListener?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDrive9ProgressListener.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDrive9ProgressListener.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]

    public static func write(_ value: [Int32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int32] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrive9FileInfo: FfiConverterRustBuffer {
    typealias SwiftType = [Drive9FileInfo]

    public static func write(_ value: [Drive9FileInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrive9FileInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Drive9FileInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [Drive9FileInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrive9FileInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrive9SearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [Drive9SearchResult]

    public static func write(_ value: [Drive9SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrive9SearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Drive9SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [Drive9SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrive9SearchResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_drive9_mobile_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9canceltoken_cancel() != 18135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9canceltoken_is_cancelled() != 14246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_copy() != 4600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_delete() != 51992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_download_file() != 2993) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_find() != 51697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_grep() != 11362) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_list() != 36043) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_mkdir() != 42794) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_patch_file_parts() != 19558) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_read() != 41349) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_rename() != 5269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_sql() != 49350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_stat() != 14655) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9mobileclient_write() != 10803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_method_drive9progresslistener_on_progress() != 21944) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_constructor_drive9canceltoken_new() != 6612) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drive9_mobile_core_checksum_constructor_drive9mobileclient_new() != 15619) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDrive9ProgressListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDrive9MobileCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all